### ISSUE TITLE
scheduler=threading?

### ISSUE THREAD

**Issue by raybellwaves** [andersy005/xarray-tutorial#8]
I see in

https://render.githubusercontent.com/view/ipynb?color_mode=light&commit=6e50dba4ac1c6716755db77e1f1c4bae2625a0d0&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616e64657273793030352f7861727261792d7475746f7269616c2f366535306462613461633163363731363735356462373765316631633462616532363235613064302f6e6f7465626f6f6b732f31312d6461736b2d64697374726962757465642e6970796e62&nwo=andersy005%2Fxarray-tutorial&path=notebooks%2F11-dask-distributed.ipynb&repository_id=373261439&repository_type=Repository#Dask-Schedulers

there is an options of scheduler=threading should this be threads? e.g. https://docs.dask.org/en/latest/setup/single-machine.html#single-machine-scheduler

**Comment by andersy005** [comment]
@raybellwaves, `threading` and `threads` options use the same scheduler:

```python
In [1]: import dask

In [7]: dask.base.named_schedulers
Out[7]: 
{'sync': <function dask.local.get_sync(dsk, keys, **kwargs)>,
 'synchronous': <function dask.local.get_sync(dsk, keys, **kwargs)>,
 'single-threaded': <function dask.local.get_sync(dsk, keys, **kwargs)>,
 'threads': <function dask.threaded.get(dsk, result, cache=None, num_workers=None, pool=None, **kwargs)>,
 'threading': <function dask.threaded.get(dsk, result, cache=None, num_workers=None, pool=None, **kwargs)>,
 'processes': <function dask.multiprocessing.get(dsk, keys, num_workers=None, func_loads=None, func_dumps=None, optimize_graph=True, pool=None, chunksize=None, **kwargs)>,
 'multiprocessing': <function dask.multiprocessing.get(dsk, keys, num_workers=None, func_loads=None, func_dumps=None, optimize_graph=True, pool=None, chunksize=None, **kwargs)>}
```

**Comment by raybellwaves** [comment]
thanks!
